version: '3.8'

services:
  db:
    image: postgres:10
    container_name: webrise_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: user_webrise
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: webrise
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: webrise_app
#    restart: unless-stopped
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/webrise
#      SPRING_DATASOURCE_USERNAME: user_webrise
#      SPRING_DATASOURCE_PASSWORD: 123456
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db


volumes:
  db_data: