name: Run Tests

on:
  push:  # Запуск при push в любую ветку
  pull_request:  # Запуск при Pull Request

jobs:  # набор задач
  test:  # Имя задачи, можно назвать как угодно (build-tests, ci-checks и т.д.)
    runs-on: ubuntu-latest  # на какой виртуальной машине будет выполняться pipeline
#    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # готовый экшен, который копирует код репозитория в виртуальную машину

      - name: Set up JDK 17
        uses: actions/setup-java@v3  # официальный экшен для установки JDK
        with:
          distribution: 'temurin'  # Использует Temurin (OpenJDK от Adoptium)
          java-version: '17'
          cache: maven

      - name: Run tests
        run: mvn test  # Запускает тесты в Maven-проекте
